# Generated by Django 3.0.3 on 2020-03-11 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('can_create_project', 'Creates a new project'),)},
        ),
    ]
