# Generated by Django 3.0.3 on 2020-03-11 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20200311_2022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('can_mark_done', 'Sets a project done.'),)},
        ),
    ]
