# Generated by Django 3.0.3 on 2020-03-11 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20200311_2024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('can_add_ticket', 'Adds a ticket'), ('can_remove_ticket', 'Removes a ticket'))},
        ),
    ]
